name: CI

on:
  push:
    branches:
      - set-ns-test
  pull_request:
    branches:
      - set-ns-test
  schedule:
    - cron:  '0 17 * * *'

jobs:
  e2e-ci:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        node-version: [12.x]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Run all e2e tests
      if: matrix.platform == 'ubuntu-latest'
      run: |
        sudo curl https://storage.googleapis.com/kpt-dev/latest/linux_amd64/kpt -o /usr/local/bin/kpt
        sudo chmod +x /usr/local/bin/kpt
        tests/e2e.sh
