apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  annotations:
    config.k8s.io/function: |
      container:
        image: gcr.io/nanyu-gke-dev/set-namespace-test-old:latest
    config.kubernetes.io/local-config: 'true'
data:
  "namespace": "example-ns"
